In [4]:
import torch

In [10]:
z=torch.zeros(3,2)
print(z)
print(z.dtype)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
torch.float32


In [11]:
#随机数主要用于实验复现
torch.manual_seed(1724)
r1=torch.rand(2,3)
print(r1)

r2=torch.rand(2,3)
print(r2)

torch.manual_seed(1729)
r3=torch.rand(2,3)
print(r3)

tensor([[0.8288, 0.4531, 0.3107],
        [0.0113, 0.2459, 0.9794]])
tensor([[0.3928, 0.8021, 0.4758],
        [0.3787, 0.1008, 0.8664]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [12]:
one=torch.ones(2,3)
print(one)
two=torch.ones(2,3)
print(two)
three=one+two
print(three)
print(three.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
torch.float32


In [16]:
r=torch.rand(2,2)*2-1
print(r)
print(torch.abs(r))
print(torch.asin(r))
print(torch.std_mean(r))
print(torch.max(r))

tensor([[ 0.3858, -0.6593],
        [-0.7231, -0.0482]])
tensor([[0.3858, 0.6593],
        [0.7231, 0.0482]])
tensor([[ 0.3961, -0.7199],
        [-0.8083, -0.0482]])
(tensor(0.5278), tensor(-0.2612))
tensor(0.3858)


In [17]:
a=torch.tensor([[1.,2.],
                [3.,4.],
                [5.,6.]])
u,s,v=torch.svd(a)
print(u)
print(s)
print(v)

tensor([[-0.2298,  0.8835],
        [-0.5247,  0.2408],
        [-0.8196, -0.4019]])
tensor([9.5255, 0.5143])
tensor([[-0.6196, -0.7849],
        [-0.7849,  0.6196]])
